# This file contains the default train settings
seed: 0          # Random seed

# Dataset
dataset: 'cifar10'    # Dataset root directory
num_workers: 8        # Number of workers in dataloader
pin_memory: True      # This can fasten or slow down data loading depending on your hardware

# Training
batch_size: 64        # Batch size
epochs: 100           # Number of epochs
learning_rate: 0.1    # Learning rate
scale_lr: False       # Scale learning rate with batch size. lr = lr*batch_size/256
momentum: 0.9         # Contribution of earlier gradient to gradient update
weight_decay: 0.00002 # Factor with which weights are added to gradient
nesterov: True        # Enable nesterov correction
do_clip: False        # Enable adaptive gradient clipping
clipping: 0.1         # Adaptive gradient clipping parameter
