wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.33.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699506404.486491
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 13
      - 23
      4: 3.9.18
      5: 0.15.12
      6: 4.33.3
      8:
      - 5
      13: linux-x86_64
lr:
  desc: null
  value: 0.0001
opt:
  desc: null
  value: adam
resume:
  desc: null
  value: false
noaug:
  desc: null
  value: false
noamp:
  desc: null
  value: false
nowandb:
  desc: null
  value: false
mixup:
  desc: null
  value: false
net:
  desc: null
  value: vit_ti
bs:
  desc: null
  value: '256'
size:
  desc: null
  value: '128'
n_epochs:
  desc: null
  value: 200
patch:
  desc: null
  value: 8
dimhead:
  desc: null
  value: 512
convkernel:
  desc: null
  value: 8
dataset:
  desc: null
  value: cifar10
